### ISSUE TITLE
which vpc module is required to run this module ?

### ISSUE THREAD

**Issue by sagespidy** [claranet/terraform-aws-aurora#15]
Hi  
i have tried this module  github.com/terraform-aws-modules/terraform-aws-vpc but no luck.

**Comment by bashtoni** [comment]
Hi,

You can create the VPC however you wish.

For general guidance on using Terraform, please see the Terraform Community documentation https://www.terraform.io/docs/extend/community/index.html

**Comment by sagespidy** [comment]
@bashtoni   You guys have done great work with this module. i want to help, to make Documentation more beginner friendly. i would love to have a word with you on the same. If possible lets  have a chat/call whatever is suitable to you.
